-- Animations.luau
-- Stores all animation IDs for every character

local Animations = {
	Default = {
		Idle = "rbxassetid://103729657684161",
		Walk = "rbxassetid://79005541514905",
		Sprint = "rbxassetid://90672762495647",
	},

	Gunn = {
		Idle = "rbxassetid://103729657684161",
		Walk = "rbxassetid://79005541514905",
		Sprint = "rbxassetid://90672762495647",
		M1_1 = "rbxassetid://0",
		M1_2 = "rbxassetid://0",
		M1_3 = "rbxassetid://0",
		M1_4 = "rbxassetid://0",
		HeavyAttack = "rbxassetid://0",
		Block = "rbxassetid://0",
	},
}

return Animations